name: apt-proxy-specify-mirrors

services:
  apt-proxy:
    image: lj020326/apt-proxy
    restart: unless-stopped
    command: --ubuntu=us:archive --debian=us:mit
    environment:
      - TZ=Etc/UTC
    ports:
      - "3142:3142"
    volumes:
      - apt-proxy-cache:/var/cache/apt-proxy

volumes:
  apt-proxy-cache:
